added stdout in json file

diff --git a/.github/workflows/code-coverage.yml b/.github/workflows/code-coverage.yml
--- a/.github/workflows/code-coverage.yml
+++ b/.github/workflows/code-coverage.yml
@@ -34,7 +34,11 @@ jobs:
          curl -fLsS -o bridge.zip ${{ vars.BRIDGECLI_LINUX64 }} && unzip -qo -d $RUNNER_TEMP bridge.zip && rm -f bridge.zip
          ls -lrt $RUNNER_TEMP
          $RUNNER_TEMP/synopsys-bridge --verbose --stage polaris > current_scan_results.json
-          defects=$(jq '.defects | length' current_scan_results.json)
+          if ! jq empty current_scan_results.json; then
+            echo "Error: Invalid JSON output from bridge-cli scan"
+            exit 1
+          fi
+          defects=$(jq '.defects | length' current_scan_results.json || jq '.results.issues | length' current_scan_results.json)
           echo "defects=${defects}" >> $GITHUB_ENV
          ls -lrt $RUNNER_TEMP
          ls -lrt ${{ github.workspace }}
